version: 2
jobs:
  build:
    working_directory: ~/zeroth
    docker:
      - image: trenpixster/elixir:1.4.4
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix test
      - run: mix credo
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - "deps"
